# Generated by Django 3.2.6 on 2021-09-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='feedback',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='emailadress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phoneno',
            new_name='phone',
        ),
    ]
