# Generated by Django 3.2.6 on 2021-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=40)),
                ('Phone_Number', models.IntegerField(max_length=15)),
                ('Table_Number', models.IntegerField(max_length=3)),
                ('Item_name', models.CharField(max_length=30)),
                ('Total_Item', models.IntegerField(max_length=30)),
                ('Address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
