# Generated by Django 3.2.6 on 2021-11-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
