# Generated by Django 3.2.6 on 2021-11-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='time',
        ),
    ]
