# Generated by Django 3.2.6 on 2022-01-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_date_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
